# -*- coding: utf-8 -*-
"""IrisPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gg6YnUkS4fRAXEXglFawE-rISTPdQpNR
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

#we'll load the Iris dataset. We can directly import it from scikit-learn's built-in datasets.

from sklearn.datasets import load_iris
iris_data = load_iris()

#convert the dataset into a pandas DataFrame and split it into features (X) and labels (y). We'll also split the data into training and testing sets
df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
df['target'] = iris_data.target

# Split features and labels
X = df.drop('target', axis=1)
y = df['target']

# Split the data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Scaling --
# perform feature scaling to normalize the input data. This is important for some machine learning algorithms, such as SVM.
# Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model Training
# train our machine learning model. In this example, we'll use a Support Vector Classifier (SVC) from scikit-learn.
# Create an SVC classifier
classifier = SVC()
# Train the model
classifier.fit(X_train, y_train)

# Model Evaluation
#Finally evaluate the trained model by making predictions on the test set and calculating the accuracy and classification report.
# Make predictions on the test set
y_pred = classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Generate classification report
report = classification_report(y_test, y_pred)
print(f"Classification Report:\n{report}")